to_do_homepage:
    path:     /hello/{name}
    defaults: { _controller: TodolistTodoBundle:Default:index }
to_do_test:
    path:     /tesst
    defaults: { _controller: TodolistTodoBundle:Default:index }